services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 27017
    volumes:
      -  ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cr73170/:/var/www/cr73170/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - py

  py:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8080
    volumes:
      - ./backend:/backend