services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      -  ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  py:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend